[env:fishbot_motion_control_four_driver_v2]
platform = espressif32
board = fishbot_motion_control_four_driver_v2
framework = arduino
upload_protocol = esptool
upload_speed = 115200
board_upload.wait_for_upload_port = no
upload_flags =
  --no-stub
monitor_filters = esp32_exception_decoder, time
